DROP TABLE ANIMALS CASCADE CONSTRAINTS;
DROP TABLE animal_info CASCADE CONSTRAINTS;
DROP TABLE animal_pen CASCADE CONSTRAINTS;
DROP TABLE animal_type CASCADE CONSTRAINTS;
DROP TABLE diet CASCADE CONSTRAINTS;
DROP TABLE food CASCADE CONSTRAINTS;
DROP TABLE medical_info CASCADE CONSTRAINTS;

DROP SEQUENCE ANIMAL_INFO_ID_ANIMALS_SEQ;
DROP SEQUENCE ANIMAL_PEN_ID_ANIMAL_PEN_SEQ;
DROP SEQUENCE ANIMAL_TYPE_ID_ANIMAL_TYPE_SEQ;
DROP SEQUENCE ANIMALS_ID_ANIMALS_SEQ;
DROP SEQUENCE DIET_ID_DIET_SEQ;
DROP SEQUENCE FOOD_ID_FOOD_SEQ;
DROP SEQUENCE MEDICAL_INFO_ID_MEDICAL_INFO;


DROP TRIGGER animal_info_birth_date_check_trg; 
DROP TRIGGER animal_info_gender_check_trg; 
DROP TRIGGER diet_quantity_check_trg; 
DROP TRIGGER food_quantity_check_trg; 
DROP TRIGGER medical_info_date_check_trg; 
DROP TRIGGER update_food_quantity_trg; 

DROP PACKAGE animal_pen_package;
DROP PACKAGE animal_type_package;
DROP PACKAGE animals_package;
DROP PACKAGE medical_info_package;
DROP PACKAGE diet_package;
DROP PACKAGE food_package;